### ISSUE TITLE
## Step 1: Create a Task List

### ISSUE THREAD

**Issue by AnonaWolf** [AnonaWolf/markdown-portfolio#4]
## Step 1: Create a Task List

A task list creates checkboxes for people with access <sup>[:book:](https://help.github.com/articles/github-glossary/#collaborator)</sup>in a repository to check off. They're very useful for tracking issues and pull requests.

If you include a task list in the body of an issue or pull request, you'll see a progress indicator in your issue list. 

Watch out! The syntax for task lists is very specific. Be sure to include the spaces where required, or else they won't render.

#### Example markup

```
- [x] Additional markup is supported, including @mentions, #references, [links](url), **emphasis**, and <del>HTML tags</del>.
- [x] List syntax is required.
  - You can nest lists below, too!
- [x] This item is completed.
- [ ] This item is not complete.
```

#### Rendered

- [x] Additional markup is supported, including @mentions, #references, [links](url), **emphasis**, and <del>HTML tags</del>.
- [x] List syntax is required.
  - You can nest lists below, too!
- [x] This item is complete.
- [ ] This item is not complete.

### :keyboard: Activity: Add a comment

1. Add a comment to this issue, using Markdown to create a list of items to complete. Your task can include any tasks you wish, or you can use this example:

       - [ ] Turn on GitHub Pages
       - [ ] Outline my portfolio
       - [ ] Introduce myself to the world

1. Use the **Preview** tab to check your markdown formatting.
1. Click **Comment**.

For a printable version of the steps in this course, check out the [Quick Reference Guide](https://lab.github.com/public/communicating-using-markdown.pdf).

<hr>
<h3 align="center">Watch below your comment for my response.</h3>

> _If you perform an expected action and don't see a response from me after a few seconds, refresh the page for your next steps._

_Originally posted by @github-learning-lab in https://github.com/AnonaWolf/markdown-portfolio/issues/1#issuecomment-570483376_

**Comment by AnonaWolf** [comment]
- [ ] Turn on GitHub Pages
- [ ] Outline my portfolio
- [ ] Introduce myself to the world
